### ISSUE TITLE
mvn install failed because of missing dependency in central

### ISSUE THREAD

**Issue by stroucki** [bugvm/bugvm#12]
[ERROR] Failed to execute goal on project bugvm-compiler: Could not resolve dependencies for project com.bugvm:bugvm-compiler:jar:1.0.0.0-SNAPSHOT: Could not find artifact com.bugvm:bugvm-soot:jar:2.5.0-1 in central (https://repo.maven.apache.org/maven2) -> [Help 1](I'm now looking at the wiki instructions)

**Comment by ghost** [comment]
fixed in bugvm-1.0.0.1-SNAPSHOT
