### ISSUE TITLE
bugvm-compiler.jar not found in "lib"

### ISSUE THREAD

**Issue by jidma** [bugvm/bugvm#120]
I tried to follow the tutorial [https://bugvm.com/compiler/](https://bugvm.com/compiler/) on a fresh clone of the repository:

    cd ~/bugvm/bugvm
    ./gradlew All

few hours later:

    path-to/bugvm/bugvm/bin$ ./bugvm
    bugvm-compiler.jar not found

So either it's a bug or the tutorial is missing something.

Thank you.

**Comment by jidma** [comment]
I tried to manually copy and rename the file `./compiler/build/libs/bugvm-compiler-1.2.2-SNAPSHOT.jar`, but I had further errors:

    bugvm: Path /path-to/bugvm/bugvm is not a valid BugVM install directory: lib/vm/ missing or invalid

**Comment by ibinti** [comment]
Command line use of bugvm may be outdated. I recently focused on using BugVM with Gradle build script. It makes everything easy and convenient than command line. Please have a look at HelloWorld example https://github.com/bugvm/bugvm-helloworld.
Command line bugvm is a simply shell script to launch bugvm-compiler and requires Envuronment set  properly.

**Comment by ibinti** [comment]
Ah, path-to/bugvm/bugvm/bin$ ./bugvm is not for running bugvm, it is source for building bugvm.

If your build is ok, the command line compiler should be in

path-to/bugvm/bugvm/build/distributions/bugvm-dist-1.2.2-SNAPSHOT.tar.gz

To use command line, follow https://bugvm.com/helloworld-console-app/ with 1.2.2-SNAPSHOT in place of 1.1.10-SNAPSHOT.

**Comment by jidma** [comment]
I see. The documentation is a bit confusing and outdated.

Thanks for the clarification.

I will give [this gradle plugin](https://bugvm.com/category/gradle-plugin/) tutorial a shot it seems up to date.

**Comment by jidma** [comment]
Gradle plugin seems to work (for iOS simulator at least).

Is there a plan to release BugVM Studio 1.2.2 anytime soon? 

It used to work fine and very smoothly until the latest iOS update.

**Comment by ibinti** [comment]
Unfortunately, there is no plan for BugVM Studio 1.2.2 release anytime soon.
Simply there is not enough man power. Any helps are welcome. Until IDEA plugin is ready, we need to rely on Gradle plugin. Not too bad.

**Comment by jidma** [comment]
I understand, I will see if I can help in any way.
Just a quick question about Gradle plugin though: how to enable log output of my device? (as we used to have in BugVM studio's console) ?

**Comment by ibinti** [comment]
I am not sure yet how the log output from the device should be redirected to the console. Launching to device is done by ideviceinstaller (https://github.com/ibinti/ideviceinstaller), which uses libimobiledevice library to communicate with the device. If you have some time, investigate how it communicate with the device. I am pretty sure there should be a way to redirect the output from the device.
