### ISSUE TITLE
task All cleans the already compiled libraries

### ISSUE THREAD

**Issue by jidma** [bugvm/bugvm#121]
`./gradlew All` takes a long time to complete.

And relaunching it even with the slightest change clears the already compiled libraries and recompiles everything (so it will take a couple of hours again).

I suspect it has something to do with the argument `--clean` in the task:

    task nativeLib(type:Exec) {
        commandLine 'bash', '-c', '. build.sh --clean'
    }

IMHO cleaning the libraries should be a separate task.

**Comment by ibinti** [comment]
You could skip nativeLib once you get the native binaries. Unless you are changing native codes, you can do build only Jars like ./gradlew buildJars. And it will take only a few minute to build Jars.
