### ISSUE TITLE
Device console output

### ISSUE THREAD

**Issue by ibinti** [bugvm/bugvm#122]

**Comment by jidma** [comment]
here's a workaround that I use using `libimobiledevice` :

    idevice_id --list // list available device UDIDs
    idevicesyslog -u <device udid> | grep <MyApplication>

**Comment by ibinti** [comment]
thanks, very cool and useful.
I will try to incorporate it.

**Comment by ibinti** [comment]
launchIOSDevice should handle actually launch on the device after install the app. Ideally then it also should spawn idevicesyslog. For the console output, slf4j logger is quite working well.

**Comment by ibinti** [comment]
use `idevicedebug` to launch the app on the device
```
idevicedebug run app_identifier
```

**Comment by ibinti** [comment]
Should investigate how all the logging outputs are messed around.

**Comment by ibinti** [comment]
use websocket logger #154
