### ISSUE TITLE
IOS_MIN_VERSION

### ISSUE THREAD

**Issue by stroucki** [bugvm/bugvm#13]
I would like to build an app on a 5.1.1 system, so I am happy to see you have reduced the IOS_MIN_VERSION from 6.0 to 5.1.1 in vm/CMakeLists.txt.

In compiler/src/main/java/com/bugvm/compiler/target/ios/IOSTarget.java lies the generation of the Info.plist file which will receive a MinimumOsVersion attribute of 6.0 by default. Can that be changed to 5.1.1 too?

**Comment by ghost** [comment]
5.1.1 change committed.
