### ISSUE TITLE
1.0.5: device32 launch Process finished with exit code -1

### ISSUE THREAD

**Issue by ghost** [bugvm/bugvm#20]

**Comment by ghost** [comment]
must be something to do with GnuTLS

**Comment by ibinti** [comment]
왜 그럴까요?

**Comment by ibinti** [comment]
[INFO] [100%] Install complete
[ERROR] AppLauncher failed with an exception:
[ERROR] com.bugvm.libimobiledevice.LibIMobileDeviceException: LOCKDOWN_E_PLIST_ERROR
[ERROR]     at com.bugvm.libimobiledevice.LockdowndClient.checkResult(LockdowndClient.java:136)
[ERROR]     at com.bugvm.libimobiledevice.LockdowndClient.getValue(LockdowndClient.java:106)
[ERROR]     at com.bugvm.libimobiledevice.util.AppLauncher.launchInternal(AppLauncher.java:682)
[ERROR]     at com.bugvm.libimobiledevice.util.AppLauncher.launch(AppLauncher.java:1047)
[ERROR]     at com.bugvm.compiler.target.ios.AppLauncherProcess$1.run(AppLauncherProcess.java:67)

**Comment by ibinti** [comment]
interestingly, iPhone-3s runs upon launch. so at the moment, iPad, and iPhone-5 have the issue that I confirmed.

**Comment by ibinti** [comment]
brew install swig

**Comment by ibinti** [comment]
--disable-openssl
 -lgnutls -lgcrypt -ltasn1

**Comment by ibinti** [comment]
back to the future version 1.1.4
