### ISSUE TITLE
[ERROR] Couldn't compile app

### ISSUE THREAD

**Issue by ibinti** [bugvm/bugvm#43]
[ERROR] Couldn't compile app
com.bugvm.compiler.CompilerException: Main class com.mycompany.myapp.Main not found
    at com.bugvm.compiler.AppCompiler.getRootClasses(AppCompiler.java:268)
    at com.bugvm.compiler.AppCompiler.compile(AppCompiler.java:450)
    at com.bugvm.compiler.AppCompiler.build(AppCompiler.java:767)
    at com.bugvm.idea.compilation.BugVmCompilerThread.doCompile(BugVmCompilerThread.java:60)
    at com.bugvm.idea.compilation.BugVmCompilerThread.run(BugVmCompilerThread.java:66)

**Comment by ibinti** [comment]
Version 1.0.9, this happens when a new project is created from the templates.
Existing projects compile without a complaint.

**Comment by ibinti** [comment]
duplicate #33

**Comment by ibinti** [comment]
is this gradle related?

**Comment by blady214** [comment]
If you don't using Gradle and moving your project form RoboVM just rename robovm.xml to bugvm.xml

**Comment by ibinti** [comment]
@blady214 It would be much appreciated if you could share some more details on how you compile the app without Gradle? Are you able to compile with other method?

**Comment by blady214** [comment]
I am not sure if I don't using Gradle but I don't hava a build.gradle file in my project but I've got robovm.xml instead of and I don't set up the gradle. I am able to build my project in RoboVM properly.

**Comment by ibinti** [comment]
With 1.1.0-SNAPSHOT, this happens when a new project is created from the templates and uses Gradle build system. Interestingly, if Maven build system is chosen, the newly created java project actually compiles and runs on simulator as well as on device.
