### ISSUE TITLE
Concentrating robovm fork effort

### ISSUE THREAD

**Issue by Zubnix** [bugvm/bugvm#47]
Hi,

Some people (me & others) think it would be wise to concentrate all robovm fork effort on a single project. See https://github.com/FlexoVM/flexovm/issues/4

Since bugvm seems to be the most active and up to date robovm fork, we thought it might be interesting to concentrate effort here. So the question is, are you ok with bugvm being further maintained/developed as a general purpose robovm fork (and are you ok with me & others helping where possible?) or do you want it to be more of a ios/mac centric prodct?

**Comment by ibinti** [comment]
By all means.

BugVM was simply my use case for iOS app when I started the project. And it suits me well at the moment.

If anyone is willing to maintain and develop BugVM as a general purpose RoboVM fork, I have no reason to refuse. It would be wonderful to have helps from you and others.

**Comment by Zubnix** [comment]
That's great to hear! Could you perhaps comment in https://github.com/FlexoVM/flexovm/issues/4 so others are aware as well (and perhaps also clear out any questions on bugvm vs other?)

**Comment by ibinti** [comment]
Submit pull requests if possible.

**Comment by Zubnix** [comment]
This is a c/p from a reply I made on another project:

The goal of that thread was to see if their could found some kind of common ground for collaboration between all the forks. Not who is in charge, or who has control on what or anything.

However looks like robovm forks are somewhat wary of collaborating out of fear of losing control (I assume?). The result is that there are now a dozen one man (pet) projects with their own isolated scope, isolated fixes and isolated pull request while there codebase is slowly deviating. This might be ok in the short term as it's mostly just maintenance work they're doing but in the long term it is not feasible.

A nice example is Android's upcoming N version, which has switched to openjdk and has/will have a lot more Java 8 support than RoboVM currently has. If any RoboVM fork wants to have some kind of long term feature, it will have to keep up on all it's supported platforms. This is most likely not a task you want to do single-handedly. Hence the need for collaboration and abandon working on islands.

Of course, in the end we can't do more than ask you nicely :)
