### ISSUE TITLE
libgdx compatibility

### ISSUE THREAD

**Issue by chancezeus** [bugvm/bugvm#56]
I think it's great that you have included support for using this as a backend for libgdx, but I have a question. There are a few libgdx plugins that depend on native components (for example box2d and freetype). These native components are implemented using the robovm structure inside their jar files (for example `gdx-freetype-platform-1.9.2-natives-ios` is structured as:

```
META-INF/MANIFEST.MF
META-INF/robovm/ios/robovm.xml
META-INF/robovm/ios/libs/libgdx-freetype.a
META-INF/robovm/tvos/robovm.xml
META-INF/robovm/tvos/libs/libgdx-freetype.a
```

I don't need or expect the tvos part to work, but I was wondering if (and how) we could get the ios part to work.

Browsing through the sources I noticed that bugvm has support for loading and using "bugvm.xml" files from jar dependencies (in a similar way robovm does it) but since there are already a few robovm based native libraries around that use the robovm structure shouldn't bugvm support both (ie. the new (META-INF/bugvm/bugvm.xml) and the old (META-INF/robovm/robovm.xml)) structure (at least until the various developers have had the time to change their jar files from using robovm to using bugvm)?

**Comment by ibinti** [comment]
Unfortunately, I do not use libgdx any more. It is best for someone who uses libgdx to maintain BugVM backend as a separate project because libgdx module is going to be removed from BugVM.

**Comment by chancezeus** [comment]
I would say that this is more a bugvm/robovm interoperability question than directly related to libgdx, but I can see the point... I'll look into the current backend and see if I have the time to fork it into a standalone project, but for the moment it looks like I need to stick to robovm since I need it for a project with a deadline...
