### ISSUE TITLE
Linker warnings

### ISSUE THREAD

**Issue by chancezeus** [bugvm/bugvm#57]
When compiling a bugvm project there are a lot of linker warnings like these:

```
---Output omitted

[WARNING] ld: warning: object file (/Users/mark/.bugvm/cache/ios/thumbv7/debug/Users/mark/.gradle/caches/modules-2/files-2.1/com.bugvm/bugvm-libgdx/1.1.0-SNAPSHOT/fdbc4a1a9ab4ffb350fc0b589b7e208ee23b5fee/bugvm-libgdx-1.1.0-SNAPSHOT.jar.extracted/META-INF/bugvm/ios/libs/libObjectAL.a(OALAudioFile.o)) was built for newer iOS version (6.1.6) than being linked (5.0)

---Output omitted

[WARNING] ld: warning: object file (/Users/mark/.bugvm-sdks/bugvm-1.0.9/lib/vm/ios/thumbv7/libgc.a(fnlz_mlc.o)) was built for newer iOS version (6.1.6) than being linked (5.0)

---Output omitted

[WARNING] ld: warning: object file (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.ios.a(emutls.c.o)) was built for newer iOS version (6.0) than being linked (5.0)

---Output omitted
```

Since I'm not planning on actually targeting 5.0 devices, I don't expect to run into problems (I suspect it is possible though), but shouldn't the bugvm sdk (a) target devices with at least the mentioned version (6.1.6+) or (b) have it's libraries and toolchain target match the 5.0 version?

**Comment by ibinti** [comment]
bugvm-libgdx is going to be removed.

**Comment by chancezeus** [comment]
As you can see not all linker warnings are related to libdx, but also to the core vm and even the xcode toolchain.

**Comment by ibinti** [comment]
I thought core vm and xcode toolchain being linked (5.0) warnings were fixed in 1.1.0-SNAPSHOT. It seems you are compiling with 1.0.9.

**Comment by ibinti** [comment]
Ok, warnings confirmed in 1.1.0-SNAPSHOT
vm **\*  was built for newer iOS version (6.1.6) than being linked (5.0)
xcode toolchain  **\* was built for newer iOS version (6.0) than being linked (5.0)

**Comment by ibinti** [comment]
1.1.5-SNAPSHOT
