### ISSUE TITLE
Import bugvm project gradle into intellij idea platform.

### ISSUE THREAD

**Issue by kadriengin** [bugvm/bugvm#61]
Hi Friends especially @ibinti :)

when i am importing my bugvm project into intellij it says "Unlinked gradle project - import gradle project" 
When i import it it giving error. I think i cant find some urls. My build.gradle file is here 

`buildscript {

```
ext {
    appName = "snopdog"
    gdxVersion = '1.7.1'
    bugVMVersion = '1.9.1-SNAPSHOT'
    box2DLightsVersion = '1.4'
    ashleyVersion = '1.6.0'
    aiVersion = '1.6.0'
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/ai/api/sdk/" }
}
dependencies {
    classpath 'com.android.tools.build:gradle:1.2.3'
    classpath 'com.bugvm:bugvm-gradle-plugin:$bugVMVersion'
}
```

}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

```
version = '1.0'


repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/ai/api/sdk/" }
    maven { url "https://oss.sonatype.org/content/repositories/releases/ai/api/sdk/" }
}
```

}

project(":desktop") {
    apply plugin: "java"

```
dependencies {
    compile project(":core")
    compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
}
```

}

project(":android") {
    apply plugin: "android"

```
configurations { natives }

dependencies {
    compile project(":core")
    compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86"
}
```

}

project(":ios") {
    apply plugin: "java"
    apply plugin: "bugvm"

```
dependencies {
    compile project(":core")
    compile "com.bugvm:bugvm-rt:$bugVMVersion"
    compile "com.bugvm:bugvm-cocoatouch:$bugVMVersion"
    compile "com.badlogicgames.gdx:gdx-backend-bugvm:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
    compile "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-ios"
}
```

}

project(":core") {
    apply plugin: "java"

```
dependencies {
    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
}
```

}

tasks.eclipse.doLast {
    delete ".project"
}`

![image](https://cloud.githubusercontent.com/assets/14088032/15772768/b66eecb6-297b-11e6-8fba-09fa8dce9d53.png)

**Comment by ibinti** [comment]
Hi,
I noticed a few points that need to be addressed.
In buildscript,  bugVMVersion = '1.9.1-SNAPSHOT'
-> latest BugVM version is 1.1.0. This is the cause of error message you are seeing.

But you are using libgdx 1.7.1, compatible BugVM version for gdx 1.7.1 is probably v1.0.6. so use  bugVMVersion = '1.0.6'. 
The main problems are in project(":ios") dependencies
compile "com.badlogicgames.gdx:gdx-backend-bugvm:$gdxVersion"
compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"

I do not think badlogicgames has gdx-backend-bugvm. They never had any bugvm backend binding. 
I had written a backend myself for gdx 1.7.1 in bugvm 1.0.6.

so change followings
compile "com.badlogicgames.gdx:gdx-backend-bugvm:$gdxVersion"
compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"

to 
compile "com.bugvm:bugvm-libgdx:$bugVMVersion"

I have not looked into gdx-box2d-platform, if it has reference to robovm, it needs to be converted to bugvm.

BTW, your computer looks interesting, Mac OSX on Windows 10. Is it some kind of virtual machine or remote desktop or vnc viewer?

**Comment by kadriengin** [comment]
No no i tried BugVM version is 1.1.0 but it gave same error than i try to chane versions for solve error. Which libgdx versiyon is compatible for bugvm 1.1.0? Is there newer version of libgdx ? if there is i want to download it.

My computer is windows 10 im connecting my friend's mac and tring to solve his error but i could not be successfull.
I will try your said, but what will we do if we want to use box2d library libgdx ios ?

**Comment by ibinti** [comment]
if you use v1.1.0, the dependency should be 'com.bugvm:bugvm-gradle:$bugVMVersion', note that bugvm-gradle, not bugvm-gradle-plugin. but v1.1.0 is not compatible with libgdx because it does not bundle gdx backend.
