### ISSUE TITLE
No @StructMember(4) defined in class com.bugvm.apple.foundation.VectorInt4

### ISSUE THREAD

**Issue by loxal** [bugvm/bugvm#62]
A Gradle build terminates with 

> 23:43:41: Executing external tasks 'clean build launchIPhoneSimulator'...
> :clean
> warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
> 1 warning
> :compileJava
> :processResources
> :classes
> :jar
> :assemble
> :compileTestJava UP-TO-DATE
> :processTestResources
> :testClasses
> :test UP-TO-DATE
> :check UP-TO-DATE
> :build
> :launchIPhoneSimulator FAILED
> 
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':launchIPhoneSimulator'.
>   
>   > Failed to launch IOS Simulator
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 6.017 secs
> No @StructMember(4) defined in class com.bugvm.apple.foundation.VectorInt4
> 23:43:50: External tasks execution finished 'clean build launchIPhoneSimulator'.

**Comment by ibinti** [comment]
it should be fixed in 1.1.1-SNAPSHOT

**Comment by loxal** [comment]
Thanks for fixing, however now I’ve got #63
