### ISSUE TITLE
Xcode 8 & iOS10

### ISSUE THREAD

**Issue by ibinti** [bugvm/bugvm#74]
1. launch to Device
2. launch to Simulator

**Comment by iAlbi93** [comment]
Hello! I'm trying BugVM with Xcode8 + iOS 10 and libidevicemobile is not working... I cannot install and simulate... Is that related to the update? (neither my old version of RoboVM works)

**Comment by iAlbi93** [comment]
com.bugvm.libimobiledevice.LibIMobileDeviceException: LOCKDOWN_E_SSL_ERROR
BugVM_ERR:  at com.bugvm.libimobiledevice.LockdowndClient.checkResult(LockdowndClient.java:138)
BugVM_ERR:  at com.bugvm.libimobiledevice.LockdowndClient.<init>(LockdowndClient.java:57)
BugVM_ERR:  at com.bugvm.libimobiledevice.util.AppLauncher.install(AppLauncher.java:540)
BugVM_ERR:  at com.bugvm.compiler.target.ios.AppLauncherProcess.execAsync(AppLauncherProcess.java:62)
BugVM_ERR:  at com.bugvm.compiler.target.AbstractTarget.doLaunch(AbstractTarget.java:490)
BugVM_ERR:  at com.bugvm.compiler.target.ios.IOSTarget.doLaunch(IOSTarget.java:604)
BugVM_ERR:  at com.bugvm.compiler.target.AbstractTarget.launch(AbstractTarget.java:486)
BugVM_ERR:  at com.bugvm.compiler.AppCompiler.launchAsync(AppCompiler.java:827)
BugVM_ERR:  at com.bugvm.compiler.AppCompiler.launch(AppCompiler.java:812)
BugVM_ERR:  at com.bugvm.compiler.AppCompiler.launch(AppCompiler.java:807)
BugVM_ERR:  at com.bugvm.compiler.AppCompiler.main(AppCompiler.java:739)
BugVM_ERR: bugvm: LOCKDOWN_E_SSL_ERROR

I get this error: is this related to my machine or to the BugVM? thanks :-)

**Comment by ibinti** [comment]
Simulator support is in progress with bugvm-sim.

**Comment by ibinti** [comment]
Simulator partly working

**Comment by ibinti** [comment]
Simulator is usable

**Comment by iAlbi93** [comment]
Thank you! When the next build of bugvm/bugvm studio? :-)

**Comment by ibinti** [comment]
Device support is in progress with libimobiledevice and ideviceinstaller.

**Comment by ibinti** [comment]
Launch to device is partly working.

**Comment by ibinti** [comment]
Launch to device is usable.

**Comment by ibinti** [comment]
1.1.10-SNAPSHOT includes this fix.
