### ISSUE TITLE
Failed to find class DTiPhoneSimulatorSystemRoot at runtime

### ISSUE THREAD

**Issue by he-sk** [bugvm/bugvm#76]
Trying to run the tutorial with version 1.1.4 prints the error message above.

This used to work a few weeks ago. In the meantime I updated Xcode. Not sure if this is related.

**Comment by ibinti** [comment]
It is Xcode 8 issue. Fix is on the way..

**Comment by ibinti** [comment]
Fixed in 1.1.10-SNAPSHOT.
