### ISSUE TITLE
Unable to follow instructions to build BugVM from scratch

### ISSUE THREAD

**Issue by teras** [bugvm/bugvm#79]
I was trying to [follow the instructions](https://bugvm.com/compiler/) to compile BugVM on my own system, but it seems some recent reorganizing has been performed.

First of all it seems that libimobiledevice is [externally accesible](https://github.com/libimobiledevice/libimobiledevice) now? Or this is what I got from the Blog.

Same thing for ios-sim ? Which repository is the correct one for this?

Is is possible to update the instructions or somehow help on this issue?

**Comment by ibinti** [comment]
As of BugVM 1.1.10-SNAPSHOT, libimobiledevice is no longer required directly. Instead BugVM uses ideviceinstaller which uses libimobiledevice library. ideviceinstaller is a console application. It is simply renamed as bugvm-device for now. In the same token, ios-sim is no longer required. BugVM uses command line console app bugvm-sim, which directly call Xcode command line tools to get the simulator support.  bugvm-sim is written from scratch in Java and built into macOS console app with BugVM. I am thinking about incorporating bugvm-sim into compiler. Other parts of build instruction should work as is.

**Comment by teras** [comment]
This is a good step forward actually.
In accordance with my [previous post](https://github.com/bugvm/bugvm/issues/80) I believe it would be a good idea to leave it as separate process, which might be wrapped in the core bugvm command.

Splitting modules and make them independent would make things easier to maintain and support I think.

Still, although I have compiled everything I found, some scripts are not properly put in place. After compilation and setting `BUGVM_HOME` to point to the correct location, I have this problem:

```
$ bugvm -help
bugvm-dist-compiler.jar not found
```

**Comment by ibinti** [comment]
Hopefully, I will update the build instructions in a day or two.

**Comment by teras** [comment]
Thank you!

**Comment by ibinti** [comment]
[Build instructions updated](https://bugvm.com/compiler/)
