### ISSUE TITLE
Separate compiler from iOS bindings

### ISSUE THREAD

**Issue by teras** [bugvm/bugvm#80]
This is more a wish than a issue.

I have the feeling that, since BugVM is clearly an open source project, thus needs more attention and contribution. But as long as it still follows the [Cathedral approach](http://www.catb.org/~esr/writings/cathedral-bazaar/hacker-history/index.html), this is going to be difficult. Instead a Bazaar approach will be now more appropriate.

Even more, it will be wishful not only to target on the constrained iOS world, but [open the gates](http://stackoverflow.com/a/29696191/339146) even for native programming. A good alternative to Java->Native doesn't exist and BugVM looks like a good candidate. I have used [XMLVM](http://xmlvm.org/) a lot in the past, but now this project is unfortunately discontinued, and BugVM could be the next alternative.

To make this possible it should be required to break up the project a bit, so it would be easier to help. And I think completely separating the java->native compiler from all the other stuff is a big but strongly required step.

The reason I write here is because I want to help. I am shattered by the size of this project and I don't know even where to start, but if you wish, I'd be glad to help with this separation to make an independent compiler (for the same targets as now) which could be used independent but hand-by-hand with the complete iOS life cycle.

**Comment by ibinti** [comment]
The top priority is to get a good grasp of internal workings of compiler, e.g. vm, llvm, the role of current android run-time and Bro. Not sure how to support Java 8. Also BugVM needs a new better way of using Bro. 

Separating to make an independent compiler is rather straight forward. But I did not seem to find need for it. When BugVM initiated, I had only one use in mind as a part of BugVM Studio.

Perhaps now is good time to have a lean-and-mean compiler.

**Comment by he-sk** [comment]
I have been researching Java byte code to native code translation and BugVM appears to be the most promising candidate. However, I agree that it would be very useful to separate the compiler from the iOS bindings.

**Comment by ibinti** [comment]
On second thought, removing iOS binding may not be straight forward due to Bro.
Anyway, I will consider seriously if there are some help from the community.

**Comment by teras** [comment]
I think this is the exact idea. A bare bones compiler does not need any annotation processing. These annotations are for easier combining Java sources with native iOS libraries. If you want to compile plain old java objects, no annotations should be required.

**Comment by ibinti** [comment]
This issue will re-open when there is a PR.
